/**
 * PDF Generation Utility
 * Generates professional PDFs from contact form data
 */

import { jsPDF } from 'jspdf';

interface ContactFormData {
  name: string;
  email: string;
  phone: string;
  formType?: string;
  message?: string;
  service?: string;
}

/**
 * Generates a PDF from contact form data
 * @param data - Contact form data
 * @returns PDF as Blob
 */
export function generateContactPDF(data: ContactFormData): Blob {
  // Create new PDF document (A4 size)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  // Brand Colors from theme.css
  const brandBlack: [number, number, number] = [13, 13, 14]; // #0d0d0e
  const brandWhite: [number, number, number] = [255, 255, 255]; // #ffffff
  const siteBg: [number, number, number] = [252, 252, 252]; // #fcfcfc
  const brandMuted: [number, number, number] = [113, 113, 130]; // Muted text color

  // Header with brand
  doc.setFillColor(...brandBlack);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(...brandWhite);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('LYNX PERMITS', margin, 20);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Contact Form Submission', margin, 30);

  // Reset text color
  doc.setTextColor(...brandBlack);

  // Form type and timestamp
  let yPos = 55;
  doc.setFontSize(10);
  doc.setTextColor(...brandMuted);
  
  const formType = data.formType || 'Contact Reach Out';
  const timestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'long',
    timeStyle: 'short',
  });

  doc.text(`Form Type: ${formType}`, margin, yPos);
  yPos += 6;
  doc.text(`Submitted: ${timestamp}`, margin, yPos);

  // Divider line
  yPos += 10;
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);

  // Contact Information Section
  yPos += 15;
  doc.setTextColor(...brandBlack);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Contact Information', margin, yPos);

  // Info box background
  yPos += 5;
  const infoBoxHeight = 45;
  doc.setFillColor(...siteBg);
  doc.roundedRect(margin, yPos, contentWidth, infoBoxHeight, 3, 3, 'F');

  // Contact details
  yPos += 10;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandBlack);

  // Name
  doc.text('👤 Name:', margin + 5, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...brandBlack);
  doc.text(data.name, margin + 30, yPos);

  // Email
  yPos += 10;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandBlack);
  doc.text('📧 Email:', margin + 5, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...brandBlack);
  doc.text(data.email, margin + 30, yPos);

  // Phone
  yPos += 10;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...brandBlack);
  doc.text('📱 Phone:', margin + 5, yPos);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...brandBlack);
  doc.text(data.phone, margin + 30, yPos);

  // Service (if provided)
  if (data.service) {
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...brandBlack);
    doc.text('🛠️ Service:', margin + 5, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...brandBlack);
    doc.text(data.service, margin + 30, yPos);
  }

  // Message section (if provided)
  if (data.message) {
    yPos += 20;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...brandBlack);
    doc.text('Message', margin, yPos);

    yPos += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    // Split message into lines to fit width
    const messageLines = doc.splitTextToSize(data.message, contentWidth - 10);
    const messageBoxHeight = Math.max(30, messageLines.length * 6 + 10);
    
    doc.setFillColor(...siteBg);
    doc.roundedRect(margin, yPos, contentWidth, messageBoxHeight, 3, 3, 'F');
    
    yPos += 8;
    doc.text(messageLines, margin + 5, yPos);
  }

  // Footer
  const footerY = pageHeight - 20;
  doc.setDrawColor(229, 231, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

  doc.setFontSize(9);
  doc.setTextColor(...brandMuted);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Lynx Permits Contact System', margin, footerY);
  doc.text(`Page 1 of 1`, pageWidth - margin - 20, footerY);

  // Return PDF as Blob
  return doc.output('blob');
}

/**
 * Generates a filename for the PDF
 * @param data - Contact form data
 * @returns Filename string
 */
export function generatePDFFilename(data: ContactFormData): string {
  const timestamp = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  const sanitizedName = data.name.replace(/[^a-zA-Z0-9]/g, '_');
  return `contact_${sanitizedName}_${timestamp}.pdf`;
}

/**
 * Downloads the PDF to the user's device
 * @param data - Contact form data
 */
export function downloadContactPDF(data: ContactFormData): void {
  const blob = generateContactPDF(data);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = generatePDFFilename(data);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
